# Generated by Django 5.1.6 on 2025-03-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_countryproduce_vaccinetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='country_produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryproduce', to='vaccine.countryproduce'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinetype', to='vaccine.vaccinetype'),
        ),
    ]
