# Generated by Django 5.1.6 on 2025-04-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_vaccine_country_produce_vaccine_vaccine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='avatarUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='userRole',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='vaccines',
        ),
        migrations.RemoveField(
            model_name='countryproduce',
            name='active',
        ),
        migrations.RemoveField(
            model_name='healthcentre',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vaccinetype',
            name='active',
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_details', to='vaccine.appointment')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_details', to='vaccine.vaccine')),
            ],
        ),
    ]
