# Generated by Django 5.1.6 on 2025-04-10 17:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_communicationvaccination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('imgNew', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imgnew')),
                ('createdAt', models.DateField(null=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vaccine',
            name='imgUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imgvaccine'),
        ),
    ]
