# Generated by Django 5.1.6 on 2025-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0005_new_vaccine_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationvaccination',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countryproduce',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthcentre',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='new',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
