# Generated by Django 5.1.6 on 2025-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0006_communicationvaccination_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='vaccine',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
