# Generated by Django 5.1.6 on 2025-04-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0007_alter_vaccine_options_vaccine_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
