# Generated by Django 5.1.6 on 2025-04-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0009_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetail',
            name='quantity',
        ),
    ]
