# Generated by Django 5.1.6 on 2025-04-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0010_remove_appointmentdetail_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthCentre',
            new_name='HealthCenter',
        ),
    ]
