# Generated by Django 5.1.6 on 2025-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0011_rename_healthcentre_healthcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_start',
            field=models.CharField(max_length=255),
        ),
    ]
