# Generated by Django 5.1.6 on 2025-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0012_alter_time_time_end_alter_time_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
