# Generated by Django 5.1.6 on 2025-04-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0013_time_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
