# Generated by Django 5.1.6 on 2025-04-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0014_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unfinished', 'Unfinished'), ('completed', 'Completed')], default='unfinished', max_length=20),
        ),
    ]
