# Generated by Django 5.1.6 on 2025-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0015_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waited', 'Waited'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='waited', max_length=20),
        ),
    ]
