# Generated by Django 5.1.6 on 2025-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0017_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
