# Generated by Django 5.1.6 on 2025-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0018_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20, null=True),
        ),
    ]
