# Generated by Django 5.1.6 on 2025-05-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0020_remove_appointment_user_appointment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vaccine.information'),
        ),
    ]
