# Generated by Django 5.1.6 on 2025-05-12 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0021_alter_appointment_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationvaccination',
            name='slotPatient',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communicationvaccination',
            name='slotStaff',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AttendantCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_communication', to='vaccine.communicationvaccination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_communication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
