# Generated by Django 5.1.6 on 2025-05-12 16:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0022_communicationvaccination_slotpatient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationvaccination',
            name='imgUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imgvaccine'),
        ),
    ]
