# Generated by Django 5.1.6 on 2025-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0023_communicationvaccination_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationvaccination',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
