# Generated by Django 5.1.6 on 2025-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0024_alter_communicationvaccination_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationvaccination',
            name='emptyPatient',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communicationvaccination',
            name='emptyStaff',
            field=models.IntegerField(null=True),
        ),
    ]
