# Generated by Django 5.1.6 on 2025-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0025_communicationvaccination_emptypatient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendantcommunication',
            name='active',
        ),
        migrations.RemoveField(
            model_name='attendantcommunication',
            name='name',
        ),
        migrations.AddField(
            model_name='attendantcommunication',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
