# Generated by Django 5.1.6 on 2025-05-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0026_remove_attendantcommunication_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendantcommunication',
            name='registration_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendantcommunication',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.communicationvaccination'),
        ),
        migrations.AlterField(
            model_name='attendantcommunication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendantcommunication',
            unique_together={('user', 'communication', 'registration_type')},
        ),
    ]
