# Generated by Django 5.1.6 on 2025-06-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0027_attendantcommunication_registration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='health_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vaccine.healthcenter'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vaccine.time'),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_details', to='vaccine.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='country_produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countryproduce', to='vaccine.countryproduce'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccinetype', to='vaccine.vaccinetype'),
        ),
    ]
