# Generated by Django 5.1.6 on 2025-06-05 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0028_alter_appointment_health_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='imgUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
