# Generated by Django 5.1.6 on 2025-06-05 10:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0029_alter_vaccine_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationvaccination',
            name='imgUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communicationvaccination',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
