# Generated by Django 5.1.6 on 2025-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0030_alter_communicationvaccination_imgurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
