# Generated by Django 5.1.6 on 2025-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0031_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='communicationvaccination',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
