version: "3.1"

recipe: default.v1
language: vi

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: MemoizationPolicy
  max_history: 5
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
  assistant_id: 20250512-204620-dark-cheese
assistant_id: 20250512-233125-weighted-engine
